Quality control of modalities features
- Check for range
- Negative values?
- Check for outliers etc

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path


PROJECT_ROOT = Path.cwd()

while not (PROJECT_ROOT / "pyproject.toml").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

print(PROJECT_ROOT)

c:\Users\eademola\pd-risk-prediction

In [18]:
from pd_risk.eda.quality_control import qc_modality

## Clinical

In [ ]:
from pd_risk.eda.quality_control import qc_modality

clinical_qc = qc_modality(
    modality="clinical",
    feature_config=PROJECT_ROOT / "configs/features/ppmi_clinical_v1.yaml",
    project_root=PROJECT_ROOT,
    feature_type="continuous",
    expected_min=0,
    allow_zero=True,
)

## DAT

In [ ]:
from pd_risk.eda.quality_control import qc_modality

dat_qc = qc_modality(
    modality="dat",
    feature_config=PROJECT_ROOT / "configs/features/ppmi_dat.yaml",
    project_root=PROJECT_ROOT,
    feature_type="continuous",
    #expected_min=0,
    allow_zero=True,
)

# NOTE: No feature engineering needed
# NOTE: Later on could consider log transformation, but only after checking the distribution
# TODO: z-transform

Loading: ppmi_risk_cohort_longitudinal.csv

======================================================================
DAT — Quality Control
======================================================================
File: ppmi_risk_cohort_longitudinal.csv

Features checked: 6
Features flagged: 2

,feature,type,n,n_missing,n_non_numeric,n_non_finite,n_negative,n_zero,n_unexpected_zero,n_below_min,n_above_max,min,max,mean,sd,n_extreme_low,n_extreme_high,n_negative_sbr,status
0,MIA_STRIATUM_L,continuous,9740,4556,0,0,0,0,0,0,0,0.07,2.24,1.121372,0.308053,11,33,0,PASS
1,MIA_STRIATUM_R,continuous,9740,4556,0,0,0,1,0,0,0,0.00,2.23,1.129379,0.306339,22,33,0,PASS
2,MIA_CAUDATE_L,continuous,9740,4556,0,0,1,0,0,0,0,-0.02,2.42,0.962930,0.338049,6,48,1,FLAG
3,MIA_CAUDATE_R,continuous,9740,4556,0,0,2,0,0,0,0,-0.09,2.42,0.960095,0.334736,4,59,2,FLAG
4,MIA_PUTAMEN_L,continuous,9740,4556,0,0,0,0,0,0,0,0.01,2.81,1.235710,0.360829,11,33,0,PASS
5,MIA_PUTAMEN_R,continuous,9740,4556,0,0,0,1,0,0,0,0.00,2.84,1.259539,0.364889,22,29,0,PASS

## MRI

In [ ]:
from pd_risk.eda.quality_control import qc_modality

mri_qc = qc_modality(
    modality="mri",
    dataset = "cortical_thickness",
    feature_config=PROJECT_ROOT / "configs/features/ppmi_mri.yaml",
    project_root=PROJECT_ROOT,
    #feature_type="continuous",
    #expected_min=0,
    #allow_zero=True,
)

# TODO: z-transform

Loading: FS7_APARC_CTH_28Jul2026.csv

======================================================================
MRI / cortical_thickness — Quality Control
======================================================================
File: FS7_APARC_CTH_28Jul2026.csv

Features checked: 70
Features flagged: 1

,feature,type,n,n_missing,n_non_numeric,n_non_finite,n_negative,n_zero,n_unexpected_zero,n_below_min,n_above_max,min,max,mean,sd,n_extreme_low,n_extreme_high,n_nonpositive,status
0,lh_bankssts,continuous,1716,0,0,0,0,0,0,0,0,0.98600,3.16500,2.383922,0.246690,60,3,0,PASS
1,lh_caudalanteriorcingulate,continuous,1716,0,0,0,0,0,0,0,0,0.94300,3.13600,2.359913,0.263492,37,15,0,PASS
2,lh_caudalmiddlefrontal,continuous,1716,0,0,0,0,0,0,0,0,1.25500,3.06900,2.366280,0.229920,72,1,0,PASS
3,lh_cuneus,continuous,1716,0,0,0,0,0,0,0,0,0.99000,2.29100,1.710124,0.158912,22,6,0,PASS
4,lh_entorhinal,continuous,1716,0,0,0,0,0,0,0,0,1.44900,4.24500,3.323658,0.339213,68,6,0,PASS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,rh_frontalpole,continuous,1716,0,0,0,0,0,0,0,0,1.17300,3.83700,2.662043,0.308692,29,20,0,PASS
66,rh_temporalpole,continuous,1716,0,0,0,0,0,0,0,0,1.63600,4.74700,3.681903,0.383359,80,6,0,PASS
67,rh_transversetemporal,continuous,1716,0,0,0,0,0,0,0,0,0.90500,3.22300,2.161956,0.302710,30,1,0,PASS
68,rh_insula,continuous,1716,0,0,0,0,0,0,0,0,1.29300,3.66100,2.917469,0.271770,51,7,0,PASS
69,rh_MeanThickness,continuous,1716,0,0,0,0,0,0,0,0,1.47402,2.69415,2.342405,0.164137,55,0,0,PASS

In [ ]:
from pd_risk.eda.quality_control import qc_modality

mri_qc = qc_modality(
    modality="mri",
    dataset = "cortical_surface_area",
    feature_config=PROJECT_ROOT / "configs/features/ppmi_mri.yaml",
    project_root=PROJECT_ROOT,
    feature_type="continuous",
    expected_min=0,
    allow_zero=True,
)
# TODO: SA_adjusted = SA - beta x eTIV (I can get eTIV) from freesurfer
# Then: TODO:  z-transform with SA_adjusted (SA_adjusted-mean / std)

Loading: FS7_APARC_SA_28Jul2026.csv

======================================================================
MRI / cortical_surface_area — Quality Control
======================================================================
File: FS7_APARC_SA_28Jul2026.csv

Features checked: 70
Features flagged: 1

,feature,type,n,n_missing,n_non_numeric,n_non_finite,n_negative,n_zero,n_unexpected_zero,n_below_min,n_above_max,min,max,mean,sd,n_extreme_low,n_extreme_high,n_nonpositive,status
0,lh_bankssts,continuous,1716,0,0,0,0,0,0,0,0,462.0,1907.0,977.664918,184.385583,3,35,0,PASS
1,lh_caudalanteriorcingulate,continuous,1716,0,0,0,0,0,0,0,0,124.0,3459.0,619.619464,165.266317,2,48,0,PASS
2,lh_caudalmiddlefrontal,continuous,1716,0,0,0,0,0,0,0,0,1164.0,3773.0,2164.782634,353.042369,1,16,0,PASS
3,lh_cuneus,continuous,1716,0,0,0,0,0,0,0,0,725.0,2370.0,1523.024476,237.605773,8,12,0,PASS
4,lh_entorhinal,continuous,1716,0,0,0,0,0,0,0,0,220.0,1263.0,453.700466,102.432707,0,39,0,PASS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,rh_frontalpole,continuous,1716,0,0,0,0,0,0,0,0,193.0,672.0,329.613054,40.149916,6,17,0,PASS
66,rh_temporalpole,continuous,1716,0,0,0,0,0,0,0,0,229.0,905.0,478.214452,68.439291,5,25,0,PASS
67,rh_transversetemporal,continuous,1716,0,0,0,0,0,0,0,0,82.0,584.0,321.881119,48.635131,10,27,0,PASS
68,rh_insula,continuous,1716,0,0,0,0,0,0,0,0,1477.0,4342.0,2274.865967,311.634286,0,22,0,PASS
69,rh_WhiteSurfArea,continuous,1716,0,0,0,0,0,0,0,0,57575.9,126207.0,84030.968706,8307.374202,2,11,0,PASS

$\beta$

In [ ]:
from pd_risk.eda.quality_control import qc_modality

mri_qc = qc_modality(
    modality="mri",
    dataset = "regional_volume",
    feature_config=PROJECT_ROOT / "configs/features/ppmi_mri.yaml",
    project_root=PROJECT_ROOT,
    feature_type="continuous",
    expected_min=0,
    allow_zero=True,
)

# TODO: V_adjusted = V- beta(eTIV)
# TODO: THEN Z-transform the adjusted V

Loading: FS7_ASEG_VOL_28Jul2026.csv

======================================================================
MRI / regional_volume — Quality Control
======================================================================
File: FS7_ASEG_VOL_28Jul2026.csv

Features checked: 32
Features flagged: 0

,feature,type,n,n_missing,n_non_numeric,n_non_finite,n_negative,n_zero,n_unexpected_zero,n_below_min,n_above_max,min,max,mean,sd,n_extreme_low,n_extreme_high,status
0,Left_Caudate,continuous,1713,0,0,0,0,0,0,0,0,1277.4,5635.2,3.240161e+03,477.107970,7,21,PASS
1,Right_Caudate,continuous,1713,0,0,0,0,0,0,0,0,986.6,5678.2,3.330121e+03,501.258514,10,15,PASS
2,Left_Putamen,continuous,1713,0,0,0,0,0,0,0,0,1806.0,7369.2,4.392779e+03,606.631336,10,18,PASS
3,Right_Putamen,continuous,1713,0,0,0,0,0,0,0,0,1285.3,8840.0,4.477376e+03,604.879506,12,15,PASS
4,Left_Pallidum,continuous,1713,0,0,0,0,0,0,0,0,1014.0,3075.5,1.955756e+03,276.619080,3,19,PASS
5,Right_Pallidum,continuous,1713,0,0,0,0,0,0,0,0,860.7,3893.3,1.912632e+03,287.362201,3,28,PASS
6,Left_Accumbens_area,continuous,1713,0,0,0,0,0,0,0,0,63.6,916.0,4.299447e+02,127.899149,1,11,PASS
7,Right_Accumbens_area,continuous,1713,0,0,0,0,0,0,0,0,32.5,956.6,5.251445e+02,115.973502,2,15,PASS
8,Left_Thalamus,continuous,1713,0,0,0,0,0,0,0,0,4411.4,11441.8,7.063796e+03,969.283527,1,27,PASS
9,Right_Thalamus,continuous,1713,0,0,0,0,0,0,0,0,4252.6,10522.7,6.973385e+03,921.381176,4,21,PASS
10,Left_Hippocampus,continuous,1713,0,0,0,0,0,0,0,0,1169.1,6040.5,4.031903e+03,477.685994,8,11,PASS
11,Right_Hippocampus,continuous,1713,0,0,0,0,0,0,0,0,1922.0,5863.7,4.136321e+03,500.759909,12,11,PASS
12,Left_Amygdala,continuous,1713,0,0,0,0,0,0,0,0,403.8,2887.8,1.589742e+03,288.217216,7,12,PASS
13,Right_Amygdala,continuous,1713,0,0,0,0,0,0,0,0,635.1,2743.2,1.733669e+03,262.436964,14,12,PASS
14,Left_Cerebellum_Cortex,continuous,1713,0,0,0,0,0,0,0,0,15845.1,75251.4,5.205138e+04,6194.009855,19,16,PASS
15,Right_Cerebellum_Cortex,continuous,1713,0,0,0,0,0,0,0,0,15873.2,76571.0,5.286977e+04,6314.087517,19,17,PASS
16,Left_Cerebellum_White_Matter,continuous,1713,0,0,0,0,0,0,0,0,6130.8,29617.6,1.521211e+04,2541.318856,8,30,PASS
17,Right_Cerebellum_White_Matter,continuous,1713,0,0,0,0,0,0,0,0,5357.3,27555.0,1.461645e+04,2306.277038,5,23,PASS
18,Left_Lateral_Ventricle,continuous,1713,0,0,0,0,0,0,0,0,2917.5,73878.3,1.443141e+04,8588.817344,0,93,PASS
19,Right_Lateral_Ventricle,continuous,1713,0,0,0,0,0,0,0,0,2313.3,66903.7,1.313551e+04,7756.221696,0,80,PASS
20,Left_Inf_Lat_Vent,continuous,1713,0,0,0,0,0,0,0,0,2.5,3774.0,4.839998e+02,374.526058,0,120,PASS
21,Right_Inf_Lat_Vent,continuous,1713,0,0,0,0,0,0,0,0,12.0,3054.0,4.931273e+02,341.143652,0,95,PASS
22,CSF,continuous,1713,0,0,0,0,0,0,0,0,507.6,4878.6,1.209661e+03,324.485033,0,45,PASS
23,BrainSegVol,continuous,1713,0,0,0,0,0,0,0,0,837214.0,1693160.0,1.153651e+06,121964.828807,0,18,PASS
24,TotalGrayVol,continuous,1713,0,0,0,0,0,0,0,0,348553.0,832636.0,5.910680e+05,62608.302715,22,5,PASS
25,CortexVol,continuous,1713,0,0,0,0,0,0,0,0,221765.0,635523.0,4.308063e+05,51927.010814,37,8,PASS
26,SubCortGrayVol,continuous,1713,0,0,0,0,0,0,0,0,38477.0,74616.0,5.534911e+04,5560.258478,4,12,PASS
27,CerebralWhiteMatterVol,continuous,1713,0,0,0,0,0,0,0,0,335837.0,1083470.0,5.012168e+05,87968.071346,0,52,PASS
28,SupraTentorialVol,continuous,1713,0,0,0,0,0,0,0,0,735181.0,1538810.0,1.020183e+06,112198.024750,0,20,PASS
29,SupraTentorialVolNotVent,continuous,1713,0,0,0,0,0,0,0,0,717559.0,1481860.0,9.862173e+05,108510.905919,0,22,PASS
30,BrainSegVolNotVent,continuous,1713,0,0,0,0,0,0,0,0,819592.0,1630650.0,1.119686e+06,118391.598754,0,18,PASS
31,EstimatedTotalIntraCranialVol,continuous,1713,0,0,0,0,0,0,0,0,912950.0,2172210.0,1.549825e+06,175565.547425,3,5,PASS

## Biospecimen

In [40]:
from pd_risk.eda.quality_control import qc_modality

biospecimen_qc = qc_modality(
    modality="biospecimen",
    feature_config=PROJECT_ROOT / "configs/features/ppmi_biospecimen.yaml",
    project_root=PROJECT_ROOT,
    feature_type="categorical",
    dataset = "saa",
    #expected_min=0,
    allow_zero=True,
)

# Count positive, negative and inconclusive groups
# TODO: One hot encoding for the three classes

Loading: SAA_Biospecimen_Analysis_Results_28Jul2026.csv

======================================================================
BIOSPECIMEN / saa — Quality Control
======================================================================
File: SAA_Biospecimen_Analysis_Results_28Jul2026.csv

Features checked: 1
Features flagged: 0

,feature,type,n,n_missing,n_unique,unique_values,unexpected_values,n_unexpected,status
0,SAA_Status,categorical,5086,0,3,"[Inconclusive, Negative, Positive]",[],0,PASS

## Genetics

| Feature(s)    | Raw representation | Preprocessing             |
| ------------- | ------------------ | ------------------------- |
| LRRK2         | `0` / variant      | **Binary carrier: 0/1**   |
| GBA           | `0` / variant      | **Binary carrier: 0/1**   |
| SNCA          | `0` / variant      | **Binary carrier: 0/1**   |
| PRKN          | `0` / variant      | **Binary carrier: 0/1**   |
| PARK7         | `0` / variant      | **Binary carrier: 0/1**   |
| PINK1         | `0` / variant      | **Binary carrier: 0/1**   |
| VPS35         | `0` / variant      | **Binary carrier: 0/1**   |
| APOE          | 6 genotypes        | **Categorical / one-hot** |
| PATHVAR_COUNT | 0–3                | **Keep as count**         |


**For APOE, keep only APOE-e4**

In [43]:
from pd_risk.eda.quality_control import qc_modality

genetics_qc = qc_modality(
    modality="genetics",
    feature_config=PROJECT_ROOT / "configs/features/ppmi_genetics.yaml",
    project_root=PROJECT_ROOT,
    feature_type="categorical",
    dataset = "pathogenic_variants",
    expected_min=0,
    allow_zero=True,
)

Loading: iu_genetic_consensus_20251025_28Jul2026.csv

======================================================================
GENETICS / pathogenic_variants — Quality Control
======================================================================
File: iu_genetic_consensus_20251025_28Jul2026.csv

Features checked: 9
Features flagged: 0

,feature,type,n,n_missing,n_unique,unique_values,unexpected_values,n_unexpected,status
0,LRRK2,categorical,6265,336,8,"[0, G2019S, G2019S/G2019S, I2020T, N1437H, R14...",[],0,PASS
1,GBA,categorical,6265,2164,13,"[0, F255Y, IVS2+1G>A, L29Afs*18, L483P, N409S,...",[],0,PASS
2,SNCA,categorical,6265,3178,3,"[0, A53T, duplication]",[],0,PASS
3,PRKN,categorical,6265,3254,17,"[0, <DEL>chr6:162002000-162066790, <DEL>chr6:1...",[],0,PASS
4,PARK7,categorical,6265,3251,2,"[0, P127S]",[],0,PASS
5,PINK1,categorical,6265,3251,3,"[0, F104Sfs*3, R492X]",[],0,PASS
6,VPS35,categorical,6265,3251,2,"[0, R524Q]",[],0,PASS
7,APOE,categorical,6265,2011,6,"[E2/E2, E2/E3, E2/E4, E3/E3, E3/E4, E4/E4]",[],0,PASS
8,PATHVAR_COUNT,categorical,6265,1,4,"[0.0, 1.0, 2.0, 3.0]",[],0,PASS

In [53]:
from pd_risk.eda.quality_control import qc_modality

genetics_qc = qc_modality(
    modality="genetics",
    feature_config=PROJECT_ROOT / "configs/features/ppmi_genetics.yaml",
    project_root=PROJECT_ROOT,
    feature_type="continuous",
    dataset = "polygenic_risk",
    #expected_min=0,
    #allow_zero=True,
)

# TODO: keep as it is, do not z-score. I already has zero mean and 1 std, Both PRS and PCs
# TODO: INFPop is the population, AFR, EAS, EUR, OTHER

Loading: PPMI_Project_9001_20250624_28Jul2026.csv

======================================================================
GENETICS / polygenic_risk — Quality Control
======================================================================
File: PPMI_Project_9001_20250624_28Jul2026.csv

Features checked: 17
Features flagged: 17

,feature,type,n,n_missing,n_non_numeric,n_non_finite,n_negative,n_zero,n_unexpected_zero,n_below_min,n_above_max,min,max,mean,sd,n_extreme_low,n_extreme_high,status
0,Genetic_PRS_PRS88,continuous,1319,0,0,0,791,0,0,0,0,-2.337652,3.816413,6.464377e-17,1.000379,0,19,FLAG
1,Genetic_PRS_PRS83,continuous,1319,0,0,0,645,0,0,0,0,-3.312192,3.030302,-1.077396e-17,1.000379,5,3,FLAG
2,Genetic_PRS_PRSp90,continuous,1319,0,0,0,786,0,0,0,0,-2.282403,3.767904,-4.309584e-17,1.000379,0,16,FLAG
3,Genetic_PRS_PRSp88,continuous,1319,0,0,0,676,0,0,0,0,-3.036565,3.401824,1.616094e-17,1.000379,2,5,FLAG
4,Genetic_PRS_PRSp87,continuous,1319,0,0,0,822,0,0,0,0,-2.166482,3.930887,1.077396e-17,1.000379,0,67,FLAG
5,Genetic_PRS_PRSp85,continuous,1319,0,0,0,654,0,0,0,0,-3.185922,3.135496,-2.693490e-17,1.000379,6,3,FLAG
6,Genetic_PRS_PC1,continuous,1319,0,0,0,825,0,0,0,0,-0.646832,8.292067,5.117632e-17,1.000379,0,53,FLAG
7,Genetic_PRS_PC2,continuous,1319,0,0,0,869,0,0,0,0,-4.062297,9.372544,5.386981e-18,1.000379,27,42,FLAG
8,Genetic_PRS_PC3,continuous,1319,0,0,0,518,0,0,0,0,-1.895891,1.433263,-8.619169e-17,1.000379,0,0,FLAG
9,Genetic_PRS_PC4,continuous,1319,0,0,0,543,0,0,0,0,-2.639345,9.772250,-1.077396e-16,1.000379,0,4,FLAG
10,Genetic_PRS_PC5,continuous,1319,0,0,0,551,0,0,0,0,-11.079329,4.502278,1.346745e-17,1.000379,28,11,FLAG
11,Genetic_PRS_PC6,continuous,1319,0,0,0,544,0,0,0,0,-4.424759,2.061959,-4.309584e-17,1.000379,69,0,FLAG
12,Genetic_PRS_PC7,continuous,1319,0,0,0,643,0,0,0,0,-3.671114,2.063224,8.080471e-18,1.000379,3,0,FLAG
13,Genetic_PRS_PC8,continuous,1319,0,0,0,633,0,0,0,0,-3.084529,10.699389,2.154792e-17,1.000379,70,24,FLAG
14,Genetic_PRS_PC9,continuous,1319,0,0,0,653,0,0,0,0,-4.303961,3.173051,0.000000e+00,1.000379,3,5,FLAG
15,Genetic_PRS_PC10,continuous,1319,0,0,0,668,0,0,0,0,-6.058526,3.685606,1.212071e-17,1.000379,4,6,FLAG
16,Genetic_PRS_InfPop,continuous,1319,0,1319,0,0,0,0,0,0,NaN,NaN,NaN,NaN,0,0,FLAG